### PR TITLE
[BUG]: Add Gateway port settings which is missing from some tasks 

### PR DESCRIPTION
**Pull request by coulof**
# Description
The port is not specify and therefore when customized it failed to install

If fixed and check for PowerFlex 3.x only

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, pep8, linting, or security issues
- [ ] I have performed Ansible Sanity test using --docker default
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Tested manually on my system

### CODE REVIEW

**Comment by ansible-collections-svc** [comment]
Can one of the admins verify this patch?

**Review by anupamaloke — APPROVED** [review]
LGTM

**Comment by coulof** [comment]
> Please fix the ansible lint issues associated with this PR.

Fixed

**Review by sachin-apa — CHANGES_REQUESTED** [review]
Can you please also add `port` under default.yml under the respective roles with the default value 443 Or else the role will fail with the error `port variable not found` when not available in the inventory.
this is because port is default to 443 as per the argument spec and docs.

**Comment by coulof** [comment]
> Can you please also add `port` under default.yml under the respective roles with the default value 443 Or else the role will fail with the error `port variable not found` when not available in the inventory. this is because port is default to 443 as per the argument spec and docs.

Isn't it already given in all the [argument_spec.yml](https://github.com/search?q=repo%3Adell%2Fansible-powerflex%20argument_spec.yml&type=code) files ?

**Comment by sachin-apa** [comment]
> @sachin-apa
> 
> Isn't it already given in all the [argument_spec.yml](https://github.com/search?q=repo%3Adell%2Fansible-powerflex%20argument_spec.yml&type=code) files ?

@coulof  Yes It is, but it doesn't mean that the value is defaulted, argument spec in role is used only for documentation and validation but the actual default value always comes from default.yml file. please refer [here](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#specification-format)
image

**Comment by coulof** [comment]
@sachin-apa, changed the `defaults/main.yaml`. Is it ok now ?
Thx.

**Review by sachin-apa — APPROVED** [review]

**Comment by coulof** [comment]
Closing without merge due to the linter issue.

The earlier commits were working and testing.

@Jennifer-John I let you decided what to do w.r.t. the configurable port for the API gateway.

**Pull request closed without merging**
