### PR TITLE
UT script for Resource Group module

### PR DESCRIPTION
**Pull request by felixs88**
# Description
UT script for Resource group module

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, pep8, linting, or security issues
- [x] I have performed Ansible Sanity test using --docker default
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x]  Unit testing
- [x]  Functional testing
- [ ]  Regression testing

### CODE REVIEW

**Comment by ansible-collections-svc** [comment]
Can one of the admins verify this patch?

**Comment by meenakshidembi691** [comment]
run e2e

**Review by sachin-apa — APPROVED** [review]

**Comment by Jennifer-John** [comment]
@felixs88 can we push these commits as part of resource group dev PR, to validate the UT actions and code coverage?

**Comment by felixs88** [comment]
Closing this PR, because UT script is updated as part of the module PR #42

**Pull request closed without merging**
